server:
  port: 8083

spring:
  redis:
    cluster:
      nodes: ip:port,ip:port,ip:port
    lettuce:
      pool:
        max-active: 250
        max-wait: 500ms
        max-idle: 50
        min-idle: 10

dubbo:
  application:
    name: rpc-web
  registry:
    check: false
    id: zkreg
    protocol: zookeeper
    address: 127.0.0.1:2181
  consumer:
    check: false
    group: daily
    version: 1.0.0

management:
  server:
    port: 10013
