server:
  port: 8083

spring:
  redis:
    cluster:
      nodes: ip:port,ip:port,ip:port
    lettuce:
      pool:
        max-active: 250
        max-wait: 500ms
        max-idle: 50
        min-idle: 10

#dubbo:
#  application:
#    name: rpc-web
#  registry:
#    protocol: zookeeper
#    address: ${ZOOKEEPER_SERVER:127.0.0.1:2181}
#  consumer:
#    group: ${SPRING_SERVICE:daily}

management:
  server:
    port: 10013
